services:
  hani-db:
    image: pgvector/pgvector:pg15
    container_name: hani-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - hani-db-data:/var/lib/postgresql/data

volumes:
  hani-db-data: